{"n_dim": 8, "n_trials": 30, "objective": "qing_on_cube", "white": "bobyqa_noise", "black": "ultraopt_gbrt", "traceback": ["passing", "Traceback (most recent call last):\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/comparison/eloratings.py\", line 79, in optimizer_game\n    with_count=True)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 47, in ultraopt_gbrt_cube\n    method='GBRT')\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 31, in ultraopt_cube_factory\n    n_jobs=1, show_progressbar=False, parallel_strategy=\"Serial\" )\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/facade/fmin.py\", line 106, in fmin\n    opt_.tell(config, loss)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 63, in tell\n    self.new_result(job, update_model=update_model)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 101, in new_result\n    self._new_result(budget, vectors, losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/bo/sampling_sort_opt.py\", line 72, in _new_result\n    y_obvs = self.loss_transformer.fit_transform(losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 41, in fit_transform\n    y = super(LogScaledLossTransformer, self).fit_transform(y)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 17, in fit_transform\n    y[y >= ERR_LOSS] = y[y < ERR_LOSS].max() + 0.1\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/numpy/core/_methods.py\", line 39, in _amax\n    return umr_maximum(a, axis, None, out, keepdims, initial, where)\nValueError: zero-size array to reduction operation maximum which has no identity\n"], "best_val": [79756.74616573167, null], "best_x": [[0.4646382015175754, 0.46464004713929075, 0.464641892761006, 0.46464373838272127, 0.46464558400443656, 0.4646474296261519, 0.46464927524786714, 0.4646511208695825], null], "feval_count": [30, null], "n_trials_instructed": [30, 30], "passing": [true, false], "completed": false, "winner": "incomplete", "points": null}