{"n_dim": 34, "n_trials": 210, "objective": "booth_on_cube", "white": "hyperopt_atpe", "black": "ultraopt_forest", "traceback": ["passing", "Traceback (most recent call last):\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/comparison/eloratings.py\", line 79, in optimizer_game\n    with_count=True)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 43, in ultraopt_forest_cube\n    method='Forest')\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 31, in ultraopt_cube_factory\n    n_jobs=1, show_progressbar=False, parallel_strategy=\"Serial\" )\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/facade/fmin.py\", line 106, in fmin\n    opt_.tell(config, loss)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 63, in tell\n    self.new_result(job, update_model=update_model)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 101, in new_result\n    self._new_result(budget, vectors, losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/bo/sampling_sort_opt.py\", line 72, in _new_result\n    y_obvs = self.loss_transformer.fit_transform(losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 41, in fit_transform\n    y = super(LogScaledLossTransformer, self).fit_transform(y)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 17, in fit_transform\n    y[y >= ERR_LOSS] = y[y < ERR_LOSS].max() + 0.1\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/numpy/core/_methods.py\", line 39, in _amax\n    return umr_maximum(a, axis, None, out, keepdims, initial, where)\nValueError: zero-size array to reduction operation maximum which has no identity\n"], "best_val": [6744515.502867288, null], "best_x": [[0.41903123347673443, 0.6577991506562338, 0.3299590721875476, 0.6837347764983159, 0.7843195404214314, 0.5497137438295384, 0.23798177482460076, 0.893964411389365, 0.7506937695499158, 0.655048320382906, 0.6041833444623453, 0.4920664476134654, 0.17135350535288713, 0.4434742015928356, 0.632063828250157, 0.37544349743400435, 0.7533004245240403, 0.418240675454966, 0.38946097874541635, 0.6553920910441027, 0.4162167538976235, 0.13923061335574, 0.07254374800802432, 0.2911964880515213, 0.13086714949360367, 0.15836516599698847, 0.4445710254810111, 0.10858217324710509, 0.6004113239657447, 0.5166521742583587, 0.4388649814044322, 0.6012163955028486, 0.03726337685496109, 0.2245465501632086], null], "feval_count": [210, null], "n_trials_instructed": [210, 210], "passing": [true, false], "completed": false, "winner": "incomplete", "points": null}