{"n_dim": 34, "n_trials": 130, "objective": "landscapes_combo1_on_cube", "white": "optuna_random_clone_2", "black": "ultraopt_forest", "traceback": ["passing", "Traceback (most recent call last):\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/comparison/eloratings.py\", line 79, in optimizer_game\n    with_count=True)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 43, in ultraopt_forest_cube\n    method='Forest')\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 31, in ultraopt_cube_factory\n    n_jobs=1, show_progressbar=False, parallel_strategy=\"Serial\" )\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/facade/fmin.py\", line 106, in fmin\n    opt_.tell(config, loss)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 63, in tell\n    self.new_result(job, update_model=update_model)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 101, in new_result\n    self._new_result(budget, vectors, losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/bo/sampling_sort_opt.py\", line 72, in _new_result\n    y_obvs = self.loss_transformer.fit_transform(losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 41, in fit_transform\n    y = super(LogScaledLossTransformer, self).fit_transform(y)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 17, in fit_transform\n    y[y >= ERR_LOSS] = y[y < ERR_LOSS].max() + 0.1\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/numpy/core/_methods.py\", line 39, in _amax\n    return umr_maximum(a, axis, None, out, keepdims, initial, where)\nValueError: zero-size array to reduction operation maximum which has no identity\n"], "best_val": [13107505986205.184, null], "best_x": [[0.35018406371351585, 0.10468613916354375, 0.1322866121077303, 0.32673679508138054, 0.09600691742162426, 0.20754212601453847, 0.4312722564408944, 0.05347506747388342, 0.6558693638291877, 0.459119651909802, 0.003950833807822018, 0.019964129532107466, 0.5844694718147043, 0.13307259070711874, 0.10025533861651059, 0.3680118485489201, 0.8899332119429003, 0.49834800282580693, 0.3458747254010226, 0.10997014020648699, 0.8902787157465873, 0.8808841894184182, 0.5718455574100026, 0.6188606185099996, 0.2718307355863365, 0.5385643205480314, 0.30027015289614234, 0.18385606894646989, 0.20744371345204193, 0.03992577018127508, 0.04067535324873783, 0.6797961315295602, 0.7910658518973496, 0.1946575340222816], null], "feval_count": [130, null], "n_trials_instructed": [130, 130], "passing": [true, false], "completed": false, "winner": "incomplete", "points": null}