{"n_dim": 34, "n_trials": 130, "objective": "deap_combo3_on_cube", "white": "platypus_smpso", "black": "ultraopt_forest", "traceback": ["passing", "Traceback (most recent call last):\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/comparison/eloratings.py\", line 79, in optimizer_game\n    with_count=True)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 43, in ultraopt_forest_cube\n    method='Forest')\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 31, in ultraopt_cube_factory\n    n_jobs=1, show_progressbar=False, parallel_strategy=\"Serial\" )\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/facade/fmin.py\", line 106, in fmin\n    opt_.tell(config, loss)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 63, in tell\n    self.new_result(job, update_model=update_model)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 101, in new_result\n    self._new_result(budget, vectors, losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/bo/sampling_sort_opt.py\", line 72, in _new_result\n    y_obvs = self.loss_transformer.fit_transform(losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 41, in fit_transform\n    y = super(LogScaledLossTransformer, self).fit_transform(y)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 17, in fit_transform\n    y[y >= ERR_LOSS] = y[y < ERR_LOSS].max() + 0.1\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/numpy/core/_methods.py\", line 39, in _amax\n    return umr_maximum(a, axis, None, out, keepdims, initial, where)\nValueError: zero-size array to reduction operation maximum which has no identity\n"], "best_val": [113471975613.86406, null], "best_x": [[0.9377140654964335, 0.043052442102240907, 0.5561704105887041, 0.3071247040372256, 0.43982693647031046, 0.6763091823263236, 0.6561255564615054, 0.41711948500925056, 0.2357831881305169, 0.49514747292139294, 0.8288923969074486, 0.8148628449575621, 0.3942307223221453, 0.255073431711086, 0.77111617409915, 0.7042874827324821, 0.4933552258574875, 0.3250115069543472, 0.8271462371237278, 0.46256369916828877, 0.8015341048380137, 0.8228403043696184, 0.735237333258787, 0.23874066409467842, 0.2072436448190399, 0.08118629255922527, 0.6849476385935686, 0.25113680437174346, 0.46559479676664206, 0.8146469612963291, 0.2910651335328105, 0.3326494993264285, 0.8389202944827331, 0.600421100481739], null], "feval_count": [100, null], "n_trials_instructed": [91, 100], "passing": [true, false], "completed": false, "winner": "incomplete", "points": null}