{"n_dim": 34, "n_trials": 130, "objective": "rosenbrock_on_cube", "white": "platypus_ibea", "black": "ultraopt_forest", "traceback": ["passing", "Traceback (most recent call last):\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/comparison/eloratings.py\", line 79, in optimizer_game\n    with_count=True)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 43, in ultraopt_forest_cube\n    method='Forest')\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 31, in ultraopt_cube_factory\n    n_jobs=1, show_progressbar=False, parallel_strategy=\"Serial\" )\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/facade/fmin.py\", line 106, in fmin\n    opt_.tell(config, loss)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 63, in tell\n    self.new_result(job, update_model=update_model)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 101, in new_result\n    self._new_result(budget, vectors, losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/bo/sampling_sort_opt.py\", line 72, in _new_result\n    y_obvs = self.loss_transformer.fit_transform(losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 41, in fit_transform\n    y = super(LogScaledLossTransformer, self).fit_transform(y)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 17, in fit_transform\n    y[y >= ERR_LOSS] = y[y < ERR_LOSS].max() + 0.1\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/numpy/core/_methods.py\", line 39, in _amax\n    return umr_maximum(a, axis, None, out, keepdims, initial, where)\nValueError: zero-size array to reduction operation maximum which has no identity\n"], "best_val": [452123644050.6661, null], "best_x": [[0.804118494913962, 0.8595108673797927, 0.8683305006112979, 0.8616726927426763, 0.28623736516044285, 0.8099260638755197, 0.8681680647057674, 0.5212062213032245, 0.4032874433678959, 0.5210071651860034, 0.29555809003832745, 0.18552320843103987, 0.4276872675116926, 0.6106753565529556, 0.7840162370261178, 0.3287427655179006, 0.642291271761106, 0.51111470192529, 0.48785908244863874, 0.7363811792031497, 0.812246824523024, 0.058880224214011845, 0.8793698117118796, 0.8922563799412286, 0.6915398080351605, 0.45628080392098425, 0.40453775918656043, 0.13718160380648092, 0.1664947549334863, 0.34620958367956733, 0.829213162100658, 0.8020984194465193, 0.46723981572114115, 0.3841699593334925], null], "feval_count": [100, null], "n_trials_instructed": [91, 100], "passing": [true, false], "completed": false, "winner": "incomplete", "points": null}