{"n_dim": 5, "n_trials": 210, "objective": "qing_on_cube", "white": "scipy_lbfgsb", "black": "ultraopt_forest", "traceback": ["passing", "Traceback (most recent call last):\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/comparison/eloratings.py\", line 79, in optimizer_game\n    with_count=True)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 43, in ultraopt_forest_cube\n    method='Forest')\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 31, in ultraopt_cube_factory\n    n_jobs=1, show_progressbar=False, parallel_strategy=\"Serial\" )\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/facade/fmin.py\", line 106, in fmin\n    opt_.tell(config, loss)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 63, in tell\n    self.new_result(job, update_model=update_model)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 101, in new_result\n    self._new_result(budget, vectors, losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/bo/sampling_sort_opt.py\", line 72, in _new_result\n    y_obvs = self.loss_transformer.fit_transform(losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 41, in fit_transform\n    y = super(LogScaledLossTransformer, self).fit_transform(y)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 17, in fit_transform\n    y[y >= ERR_LOSS] = y[y < ERR_LOSS].max() + 0.1\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/numpy/core/_methods.py\", line 39, in _amax\n    return umr_maximum(a, axis, None, out, keepdims, initial, where)\nValueError: zero-size array to reduction operation maximum which has no identity\n"], "best_val": [7.561286964437336e-08, null], "best_x": [[0.29099999504265306, 0.2914142096433007, 0.29173204609951425, 0.2919999947655101, 0.29223606329106067], null], "feval_count": [181, null], "n_trials_instructed": [210, 181], "passing": [true, false], "completed": false, "winner": "incomplete", "points": null}