{"n_dim": 34, "n_trials": 210, "objective": "powers_on_cube", "white": "scipy_nelder", "black": "ultraopt_forest", "traceback": ["passing", "Traceback (most recent call last):\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/comparison/eloratings.py\", line 79, in optimizer_game\n    with_count=True)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 43, in ultraopt_forest_cube\n    method='Forest')\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 31, in ultraopt_cube_factory\n    n_jobs=1, show_progressbar=False, parallel_strategy=\"Serial\" )\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/facade/fmin.py\", line 106, in fmin\n    opt_.tell(config, loss)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 63, in tell\n    self.new_result(job, update_model=update_model)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 101, in new_result\n    self._new_result(budget, vectors, losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/bo/sampling_sort_opt.py\", line 72, in _new_result\n    y_obvs = self.loss_transformer.fit_transform(losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 41, in fit_transform\n    y = super(LogScaledLossTransformer, self).fit_transform(y)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 17, in fit_transform\n    y[y >= ERR_LOSS] = y[y < ERR_LOSS].max() + 0.1\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/numpy/core/_methods.py\", line 39, in _amax\n    return umr_maximum(a, axis, None, out, keepdims, initial, where)\nValueError: zero-size array to reduction operation maximum which has no identity\n"], "best_val": [1351771.0114858714, null], "best_x": [[1.9963302524303092e-05, 0.00023344070337047833, -0.00015454978574031418, -0.00015109514332689014, -0.0005675354144687951, -2.1809584048189417e-05, -4.041274293043651e-05, -5.6771138984057664e-05, -0.00019990260070458293, -6.361811440609645e-05, -7.702087818916035e-05, -8.805548393539769e-05, -9.576941571903309e-05, -0.00010040735946561507, 0.00011662924900132509, -0.00019242898160989604, -0.00018476995451551295, -0.00016164497236648086, -0.00013905740080236194, -0.00038464480519203876, -1.835177432519078e-05, -5.272724041740747e-06, 4.900080781203054e-06, 0.00047886159907828326, 4.205140203747907e-05, 1.9816803947795768e-05, -3.168740766930539e-05, -8.500095604958827e-05, 0.00011076052591191785, 1.4736051609082651e-05, 0.0001975197627984834, 0.0004823578761155516, 0.0005704903482722339, 0.0008907173353184471], null], "feval_count": [211, null], "n_trials_instructed": [210, 211], "passing": [true, false], "completed": false, "winner": "incomplete", "points": null}