{"n_dim": 55, "n_trials": 80, "objective": "risk_on_cube", "white": "ultraopt_etpe", "black": "dlib_default", "traceback": ["passing", "Traceback (most recent call last):\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/comparison/eloratings.py\", line 79, in optimizer_game\n    with_count=True)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/dlibcube.py\", line 28, in dlib_default_cube\n    best_x, best_val = find_min_global(_objective, lb, ub, n_trials)\nRuntimeError: \n\nError detected at line 63.\nError detected in file /private/var/folders/g2/6p5lz9hn36vbnv165bk7yj7r0000gn/T/pip-install-ojjogyqk/dlib_836e2179ea074a8ba6ce68fbb0be6025/tools/python/src/global_optimization.cpp.\nError detected in function double call_func(py::object, const matrix<double, 0, 1> &).\n\nFailing expression was 0 < num && num < 35.\nFunctions being optimized must take between 1 and 35 scalar arguments.\n\n"], "best_val": [136.80803228568985, null], "best_x": [[0.0, 0.29475776333308823, 0.0, 0.0, 0.6295723316006568, 0.6570023660174672, 0.004257806162786371, 0.3159864066104888, 0.0, 0.041509791921444966, 0.02260855761124677, 0.0, 1.0, 0.0, 0.0, 0.42212087584894703, 0.11071246509966504, 0.0, 0.5984788164437549, 0.3412478560994251, 0.20849729186662108, 0.0, 0.952468830221135, 0.0, 0.10662696106885114, 1.0, 0.9655340815795352, 0.0, 0.0, 0.1251470299558514, 0.379540608558361, 0.10841150344852728, 1.0, 0.0971638004254374, 0.0, 0.4117279999931742, 0.22924032701978936, 0.8998085368309281, 0.0, 0.19963555885803294, 0.2784980375319044, 0.03593475043131575, 0.9611695895016721, 0.6604588018350007, 0.13709237905328, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4343591145264205, 0.5864795347440134, 0.805781686918629], null], "feval_count": [80, null], "n_trials_instructed": [80, 80], "passing": [true, false], "completed": false, "winner": "incomplete", "points": null}