{"n_dim": 55, "n_trials": 210, "objective": "deap_combo3_on_cube", "white": "ultraopt_etpe", "black": "ultraopt_forest", "traceback": ["passing", "Traceback (most recent call last):\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/comparison/eloratings.py\", line 79, in optimizer_game\n    with_count=True)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 43, in ultraopt_forest_cube\n    method='Forest')\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 31, in ultraopt_cube_factory\n    n_jobs=1, show_progressbar=False, parallel_strategy=\"Serial\" )\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/facade/fmin.py\", line 106, in fmin\n    opt_.tell(config, loss)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 63, in tell\n    self.new_result(job, update_model=update_model)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 101, in new_result\n    self._new_result(budget, vectors, losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/bo/sampling_sort_opt.py\", line 72, in _new_result\n    y_obvs = self.loss_transformer.fit_transform(losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 41, in fit_transform\n    y = super(LogScaledLossTransformer, self).fit_transform(y)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 17, in fit_transform\n    y[y >= ERR_LOSS] = y[y < ERR_LOSS].max() + 0.1\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/numpy/core/_methods.py\", line 39, in _amax\n    return umr_maximum(a, axis, None, out, keepdims, initial, where)\nValueError: zero-size array to reduction operation maximum which has no identity\n"], "best_val": [222670706932.87296, null], "best_x": [[0.8212573046720129, 0.9122082367815256, 0.45714778494629904, 0.7123397665180721, 0.7368518341007088, 0.842417588637132, 0.7088818359545462, 0.7275455592212561, 0.16883070101976028, 0.9586491259686153, 0.5973493009778531, 0.2505014246959396, 0.13678334392051938, 0.3483875111152135, 0.49171764415020336, 0.7113031723789262, 0.36544761668762304, 0.7820035810020739, 0.36269059503914225, 0.9560667599363938, 0.5327131734934678, 0.792804500850439, 0.3358731152380754, 0.14097657997115132, 0.5019659390052948, 0.6547598816421494, 0.2498596465001074, 0.14469313676316997, 0.6850225005037682, 0.45183246916418396, 0.8054605464510722, 0.2458048333436902, 0.1335766301686505, 0.790274878872813, 0.507596641173686, 0.5926756073764571, 0.1285242398215719, 0.6708799651901817, 0.1634262799766879, 0.1385437677871365, 0.1538863309528674, 0.8172499953949958, 0.8271985880723594, 0.21847484278906937, 0.6907769621902532, 0.06557133997254605, 0.2772736578792351, 0.3672286614206496, 0.7139544539594812, 0.4200356031696383, 0.6811096817217539, 0.8234972258539375, 0.4872264157505518, 0.8016208319835301, 0.5638353456170709], null], "feval_count": [210, null], "n_trials_instructed": [210, 210], "passing": [true, false], "completed": false, "winner": "incomplete", "points": null}